language: node_js

services:
  - mysql

before_script:
  - mysql -e 'create database firenze;'

node_js:
  - 'stable'
  - '0.12'

script:
  - 'npm run lint'
  - 'npm run babel'
  - 'npm run mocha:mysql-travis'
  - 'npm run mocha:memory'

notifications:
  email: false
